branches:
  except:
  - "/^untagged/"
language: node_js
os:
- linux
node_js:
- 16
script: npm run package
deploy:
# publish vsix release in github, renew token encrypted : travis setup releases --com --force -g $NEW_TOKEN
- provider: releases
  api_key:
    secure: eRce0PjaxgS2a2mWogNaDNFP2nJ7wiN3kz8DS0MwQ9SPXiDwBB1kJquXHRFrzk/Da/2kyqSKtxsssUO3TPliU5HgjlT8WANLPgLt2pgHBPUbOZqcND+xMH8puugowuLkaOE60CMu/Oz+c/ZryR12BfoEYluVDBrRL8CJ5ttxg+MZtDer4JF3tQpByGkthVEQ3KKKkFjSI/AqYXBfLxcBIe7KI65gs1nf8zcDJEY4kz2VP9Kw/i0EvwymExcYLq3ayS8TS+SfPZivyiJpkxH8IbCzbNUMiWPYuB3p7ow11Kv5bcUvEDoxmZwgh+nVVavK0I8VZ3tET6BpvKZ2j1ItFKpwiQPdX1N7JP0T0MfE98PfB3AIG318z09jMTZ3vbj6Ly/KO4LnMdYehzrAOglinqQ0GS/ehUMKsGKPh3vQMZHKzb3xaPwyAP0+PMQuZfcl+IU3YBBTB/nbEHf8pXJdFN/yX3QHayQ3+F7Ehy5GcAFhtlCmUS9RFb9CZ8gbjHMyHaHh87w+ImzHChla4OSN8dl7rV9GLZmqC3864+bYonXta6QhKDyE36bolS1VUTe8bh/4Ji+Ic+ofMYJDQH9U436ynynsAjNFhmTqyzeffOhXIO7UdhQCB7GHOQc1zDG5HJlLsA8E5ViL6DcWNuqEDEInd20hW+jPFXltKbepyMg=
  file: "*.vsix"
  skip_cleanup: 'true'
  file_glob: true
  draft: true
  on:
    repo: lefebsy/vskubi-lite
    tags: true
# publish vsix release in vscode marketplace, token is valid 1 year, renew in dev.azure.com    
- provider: script
  script: vsce publish --pat $MARKET_PERSONAL_ACCESS_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
# publish vsix release in open vsx registry for Theia : https://open-vsx.org/extension/lefebsy/vskubi-lite 
- provider: script
  script: npm install --global ovsx && npx ovsx publish ./*.vsix --pat $OPEN_MARKET_PERSONAL_ACCESS_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
  
