branches:
  except:
  - "/^untagged/"
language: node_js
os:
- linux
node_js:
- 16
script: npm run package
deploy:
- provider: releases
  api_key:
    secure: "YRkXHwEKEgnCTGDhUb8QWdmLAoC+ua9+mUcvI/w4f+m8U4aGeMyALOv3SJ1GlegdcS7nJLXMpP/q63LAM0256+3J4lBMp0VlDWqWXlsDaSzCe7LXyVRCau4ECzKMm/3biVomyJCu4D9kqd2N0dLgN82lDimJoyPwNC7+/EAepYKHs+RIk1cn+uLTgjRr3OV+mR0SsV0roGT853fdtOGQr6jfyPBu1088Kx4OHzel1lyDuWeze7RRG68kfiRtJPrgnTBABMBbOQzZqiUmFIwApWs4uUtsKtrMk8IXjaFJNo8LK3h3ehJhiS5KfurBXkYuwjGJtd9kCAVqsd8pBoegPSWuLSeiHrOWiQ9Z9q8ypifV/rV+vkJk6OZSVP2TJF5Q29xcUL0w5ctnrdJeJ3NUUu6PZ1JPBP9W8+tT6Na2HvmZu0rhkqfDn1w7LP7e8i9NwBnjlfUZvM9EQc0SwUaSHC7/cG0VTiG7IL1UuuVhqfKIhXO5r4hBj08UcIcX5wWgVMIboDCRAk2/rxo0fFfmNjQBkjgOAxFRp6nBcHa3IXZGiOX+W9SHUBi8WoYS/p17+lIArW5jaAT0K/qr1Ugf/GC6JwVY3yt1eTi8+10uul5rUcy+iP2wqmJJk59zl1RfaC8CJnGARldTUjBLc/xZ3fR3WPPRLtO1UZNCHIfRB8Q="
  skip_cleanup: 'true'
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
- provider: script
  script: vsce publish --pat $MARKET_PERSONAL_ACCESS_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
- provider: script
  script: npm install --global ovsx && npx ovsx publish ./*.vsix --pat $OPEN_MARKET_PERSONAL_ACCESS_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
