branches:
  except:
  - "/^untagged/"
language: node_js
os:
- linux
node_js:
- 16
script: npm run package
deploy:
- provider: releases
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
- provider: script
  script: vsce publish --pat $MARKET_PERSONAL_ACCESS_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
- provider: script
  script: npm install --global ovsx && npx ovsx publish ./*.vsix --pat $OPEN_MARKET_PERSONAL_ACCESS_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "*.vsix"
  on:
    repo: lefebsy/vskubi-lite
    tags: true
env:
  global:
    secure: ity/sNJmSoqOnqoMKqPC7quLNUn5iwMUsfboI2KDDtmCOlpql36aLinSKB7j+lm75WIkvqMm+4Ifw2OQjQl725BagSQT62loyWUmdCXmKHSivl/akZc8KXGDJtAEMSMVSvjttQiS5m8W+s3urQJtWHF3w334w2XFmVuByXX9RT+SsIzyuX6uPN/Mowgh9Ja77ARLu7DoZFx1QxVk0/P3gAzJcqAlyfu1y960XsofOBncFxYwQzxT0w3fPK30WBny7U4wLSI3V5ysZ0BtAVG7+NBxkUsVdqG6naCTHpUeiiEk6GjUezq677VGpB85GV9IyDnGpcwoIsgW+eGimkUN80QgzdyxTPFG5jDHJr6Qq/+AqBx/W7KqIWwlT3T5AsCX4Yhz+92OEtAaEvSGqTOoJ4UfopQKyGQJulQXOd6JY6EjJdEJa6GTm66CukCDbCeTbc6tv9YqzUbhx7iQS7DKrzouiG3fDyCcCQClerNX4HD0KbewlQxZjvky1GFlnMY+6YAglTOPX3z6QJOTtV8WhNVyIZsNislY/+7ncGyPQNWOMxHnJT++vs+zlcnrLFskc5HBxL04txeZPFcThPTGol7WKw96FROzF9PKkGz03Bn3zuqClmKGgWEQkiQv5CLedm29qZ0hL/PVP65WwwHWgbJRPZL97OAg1MnKDNoou68=
