name: Publish

on:
  push:
    tags:        
      - v*


jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Package
      run: |
        npm install
        npm run package


    - name: Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: '*.vsix'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref_name }}


    - name: Marketplace
      env:
        MARKET_PERSONAL_ACCESS_TOKEN: ${{ secrets.MARKET_PERSONAL_ACCESS_TOKEN }}
      run: |
        ls *.vsix
        npm install -g @vscode/vsce
        vsce publish --pat $MARKET_PERSONAL_ACCESS_TOKEN
