name: Publish

on:
  push:
    branches:
      - 'release/**'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: vsix
        path: .

    - name: Marketplace
      run: |
        npm install
        ls *.zip
        ls *.vsix
        ls -lisah
        vsce publish --pat $MARKET_PERSONAL_ACCESS_TOKEN
